### ISSUE TITLE
Generate a string representation of the thumbhash?

### ISSUE THREAD

**Issue by gtokman** [evanw/thumbhash#18]
I'm working on integrating this into a project and I'm wondering how I can get the `string` representation of the thumbhash.

As you know, a common use case is to generate the hashes upfront on the server and pass them in the response body with the image URI to be loaded.

I see in the demo on the GH pages that there's a string representation of the thumbhash in bytes shown, but it's not clear from the API how to output that. 

What function(s) actually output the byte `string` that is the demo?

<img width="974" alt="CleanShot 2023-03-25 at 16 45 25@2x" src="https://user-images.githubusercontent.com/12258850/227740816-ff06dde2-9b46-42fc-9e71-abf80e816da3.png">

Second, the API for iOS expects a `Data` type as a parameter to generate the `UIImage`. It works great if you have a static image as is shown in the [example](./examples/ios/ViewController.swift) but how can we use the byte string and create a `Data` type to be used for the input?

**Comment by evanw** [comment]
You can use any textual representation of the binary data that you like. It's not part of ThumbHash's API. And you can use Google to find out how to do that. For example, Swift has built-in base64 support if you'd like to use base64:

* https://developer.apple.com/documentation/foundation/data/2142853-base64encodedstring
* https://developer.apple.com/documentation/foundation/data/3126625-init

**Comment by gtokman** [comment]
@evanw Thanks for the suggestions and clarification on the API. I wasn't sure if the goal of this project was to match Blurhash API one-to-one. Specifically their deterministic input/output across platforms.

```swift
extension UIImage {
    public convenience init?(blurHash: String, size: CGSize, punch: Float = 1) {}
}
```

**Comment by nicolasparada** [comment]
Commenting here what I did.
I have a Go back-end and from there I render an image like:

```html
<img src="{{.URL}}" data-thumbhash="{{btoa .Thumbhash}}">
```

Were `URL` is the full image URL and `Thumbhash` are the thumbhash bytes. I convert them to base64 using the function `btoa`.

So, effectively, the image can look something like this:

```html
<img src="/example.jpeg" data-thumbhash="IQgKFYL/YqhDqahapoqXem+b+cmZ">
```

Then client side. I search this image and replace the image source with the thumbhash, and once the image fully loads, I replace it back again with the original URL.

```js
import { thumbHashToDataURL } from "https://unpkg.com/thumbhash@0.1.1/thumbhash.js"

const img = document.querySelector("img")
if (img.complete) {
    return
}

const b64 = img.getAttribute("data-thumbhash")
if (b64 === null) {
    return
}

const hash = Uint8Array.from(atob(b64), c => c.charCodeAt(0))

const originalSrc = img.src

img.addEventListener("load", () => {
    img.src = originalSrc
}, { once: true })

img.src = thumbHashToDataURL(hash)
```

It is basically:

```js
const base64Representation = "IQgKFYL/YqhDqahapoqXem+b+cmZ"
thumbHashToDataURL(Uint8Array.from(atob(base64Representation), c => c.charCodeAt(0)))
```

This works so its a progresive enhancement. The HTML image the browser receives contains the original image as src, so if javascript is disabled it will keep working. If the image is already cached it will just show that.
The thumbhash will be shown in the meanwhile the full image loads.

The code can be put inside a MutationObserver and apply it to all images.

**Comment by hirasso** [comment]
@nicolasparada 

thanks so much for posting this bit here! I can do a lot of things, but I will probably never learn stuff like this!

@evanw I can certainly imagine there is a lot of us frontend designers / developers that would love to use thumbhash but can't because they can't find this solution. So a very short snippet somewhere on the thumbhash website would help a lot I imagine! :)
