### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by ShivamJoker** [evanw/thumbhash#2]
It would be great if there would be an example in JavaScript on how to convert an image into thumbhash then into png url.

**Comment by evanw** [comment]
Yeah I agree. I’m planning to get some examples together. In the meantime, the best reference is the demo website source code: https://github.com/evanw/thumbhash/blob/gh-pages/index.html

**Comment by ShivamJoker** [comment]
I see. Thanks.

But we don't have access to canvas in the Node environment which would be the ideal choice of library for converting images into RGBA?


I learnt that sharp and image-js can do that but I am not sure about the performance.

Thanks.

**Comment by evanw** [comment]
I’m not familiar with doing image processing in node, sorry. You’ll have to ask someone else for recommendations.

**Comment by cijiugechu** [comment]
> I see. Thanks.
> 
> But we don't have access to canvas in the Node environment which would be the ideal choice of library for converting images into RGBA?
> 
> I learnt that sharp and image-js can do that but I am not sure about the performance.
> 
> Thanks.

You can try using [this library](https://github.com/Brooooooklyn/canvas)

**Comment by ShivamJoker** [comment]
Ok so I did bit of experiment with both sharp and rust canvas using the anime girl image.

The canvas converted it in - 39.217ms
And sharp did it in - 54.196ms

So canvas is the winner.

Here is my code:

```typescript

import { createCanvas, loadImage } from "@napi-rs/canvas";
import { rgbaToThumbHash } from "thumbhash";

async function loadImageAndConvertToHash(
  imagePath: string
): Promise<Uint8Array> {
  const maxSize = 100;
  const image = await loadImage(imagePath);
  const width = image.width;
  const height = image.height;

  const scale = Math.min(maxSize / width, maxSize / height);
  const resizedWidth = Math.floor(width * scale);
  const resizedHeight = Math.floor(height * scale);

  const canvas = createCanvas(resizedWidth, resizedHeight);
  const ctx = canvas.getContext("2d");
  ctx.drawImage(image, 0, 0, resizedWidth, resizedHeight);

  const imageData = ctx.getImageData(0, 0, width, height);
  const rgba = new Uint8Array(imageData.data.buffer);
  const hash = rgbaToThumbHash(resizedWidth, resizedHeight, rgba);
  return hash;
}

const imagePath = "./anime-girl.png"; // Replace with the path to your image

const run = async () => {
  console.time("converted-in");
  const hash = await loadImageAndConvertToHash(imagePath);
  console.timeEnd("converted-in");
  console.log("Image hash:", hash);
};

run();
```

**Comment by mbforbes** [comment]
Posting in case this helps anyone else. @ShivamJoker thank you so much for your example code, but I needed to change one line that I think is a bug:

```js
const imageData = ctx.getImageData(0, 0, width, height);
```

... should instead use the resized heights of the canvas and image:

```js
const imageData = ctx.getImageData(0, 0, resizedWidth, resizedHeight);
```

Without this, the hashes generated all rendered solid gray.

**Comment by ShivamJoker** [comment]
Hey @mbforbes I've updated the code, if it works as expected can you share some screenshots?

**Comment by mbforbes** [comment]
@ShivamJoker thanks for the quick reply and for updating your code! Sure thing, here's an example blurry image w/ b64 hash generated using your code then rendered w/ thumbhash in the browser :-)

<img width="753" alt="Screenshot 2023-07-14 at 4 42 15 PM" src="https://github.com/evanw/thumbhash/assets/1170062/ae62c3fa-7bfb-4e58-bb0e-2f6dc4a2883b">
