### ISSUE TITLE
PHP implementation

### ISSUE THREAD

**Issue by ToshY** [evanw/thumbhash#5]
Any plans to create a PHP implementation?

**Comment by SRWieZ** [comment]
Looks like @marconett beat me to it with his pull request #8 

I published this package usable with composer for my needs [SRWieZ/thumbhash](https://github.com/SRWieZ/thumbhash)  
I did take time to add tests and try different library to get the image data.
But it's rough translation of the Javascript version to PHP, it needs some polishing.

**Comment by evanw** [comment]
Closing in favor of #8.

**Comment by evanw** [comment]
@SRWieZ I've decided to link to third-party implementations instead of hosting them within this repo. You are welcome to send a PR that adds a link to your repo if/when you'd like to.
